language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      env: TOXENV=WIN
      sudo: false
    - os: linux
      dist: trusty
      sudo: false
    - os: osx
      osx_image: xcode8
addons:
  apt:
    packages:
      - g++-mingw-w64
before_script:
  - export PATH="$HOME/bin:$PATH"
  - make -f texinfo-travis.mk install_texinfo
script:
  - export REV=dirty-$(git describe --always)
  - git clone https://github.com/vitasdk/buildscripts.git
  - chmod +x *.sh
  - ./build.sh
before_deploy:
  - . ./before_deploy.sh
deploy:
  provider: releases
  api_key: $OAUTH
  file_glob: true
  file: "buildscripts/build/*.tar.bz2"
  skip_cleanup: true
  on:
    tags: false
    all_branches: true
branches:
  except:
    - /^*-v[0-9]/
